version: '3.7'
services:
  database:
    build: 
      context: .
      dockerfile: ./scripts/database/DockerFile
    container_name: database
    restart: always
    image: database:v1
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: test
      MONGO_INITDB_DATABASE: projects
    ports:
      - 9009:27017
  frontend:
    build: 
      context: .
      dockerfile: ./my-app/Dockerfile
    container_name: frontend
    restart: always
    image: frontend:v1
    ports:
      - 3000:80
  backend:
    build: 
      context: .
      dockerfile: ./backend/Dockerfile      
    container_name: backend
    restart: always
    image: backend:v1
    ports:
      - 5000:8000
    depends_on:
      - database