version: '3.8'
services:
  database:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  frontend:
    build: ./my-app
    ports:
      - 3000:3000
  backend:
    build: ./backend
    ports:
      - 5000:5000
