version: '3.7'
services:
  database:
    build: ./scripts/database
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: test
      MONGO_INITDB_DATABASE: projects
    volumes:
      - mongo: /data/db
  frontend:
    build: ./my-app
    ports:
      - 3000:80
  backend:
    build: ./backend
    ports:
      - 5000:80
