version: '3.7'
services:
  backend:
    build: 
      context: .
      dockerfile: ./Dockerfile      
    container_name: backend
    restart: always
    image: backend:v1
    ports:
      - 5000:8000