version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:16-browsers
    steps:
      - checkout
      - run: npm install
      - run: npm run jest
      - run: npm run fix-lint

workflows:
  version: 2
  build-and-test:
    jobs:
      - test
