version: '3.7'
services:
  database:
    build: 
      context: .
      dockerfile: ./DockerFile
    container_name: database
    restart: always
    image: database:v1
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: test
      MONGO_INITDB_DATABASE: projects
    ports:
      - 9009:27017
